bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls')),
    path('about/',include('about.urls')),
    path('accounts/',include('accounts.urls')),
    path('contact/',include('contact.urls')),
    path('',include('shop.urls', namespace="shop")),
    
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
	path('recommend/',views.recommend,name='recommend'),
	path('', views.product_list, name='product_list'),
    path('<category_slug>/', views.product_list, name='product_list_by_category'),
   	path('<int:id>/<slug>/', views.product_detail, name='product_detail'),
   
   ]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django.shortcuts import render, redirect,get_object_or_404
from django import forms
from django.db import models
from shop.models import Product


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,30)]

class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@login_required
@require_POST

def cart_add(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object 
    product = get_object_or_404(Product, id=product_id) 
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})

    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 2%">
        <h3 class="text-center">Your Shopping Cart</h3>
        
        
            <table class="table table-striped table-hover" style="background-color:snow">
                <thead style="background-color: teal">
                    <tr style="color: white">
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get__absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url 'cart:cart_remove' product.id %}" class="btn btn-danger">Remove</a>
                            </td>
                            <td>Rs. {{ item.price }}</td>
                            <td>Rs. {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: teal">
                    <td style="color: white"><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num" style="color: white"><b>Rs. {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>

            

        <p class="text-right">
            <a href="{% url 'shop:product_list' %}" class="btn btn-info">Continue Shopping</a>
                    {% if cart.get_total_price > 0 %}
                        <a href="{% url 'orders:order_create' %}" class="btn btn-danger"> Checkout</a>
                    {% endif %}
               
        
        </p>
        </div>
                
    </div>
{% endblock %}