bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls')),
    path('about/',include('about.urls')),
    path('accounts/',include('accounts.urls')),
    path('contact/',include('contact.urls')),
    path('',include('shop.urls', namespace="shop")),
    
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
	path('recommend/',views.recommend,name='recommend'),
	path('', views.product_list, name='product_list'),
    path('<category_slug>/', views.product_list, name='product_list_by_category'),
   	path('<int:id>/<slug>/', views.product_detail, name='product_detail'),
   
   ]

recommendation/templates/recommendation/recommend.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %} Recommendations {% endblock %}
{% block content %}

<div class="container-fluid">
    <h2>Recommendations for You </h2>
</div>
    <div class="container-fluid">
   
    <div class="row">
            {% if product_list %}
            {% for product in product_list %}
                <div class="col-sm-2 col-md-2 ">
                    <div class="thumbnail">
                        <h4>{{product.name}}</h4>
                        <a href="{% url 'shop:product_detail' id %}">
                            <img src="{{ product.image.url }}" class="img-responsive">
                        </a>
                        <h5>{{product.category}}</h5>
                        <div class="caption">
                            <a href="{% url 'shop:product_detail' id %}" class="btn btn-primary btn-sm" role="button">Give Rating</a>    
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
        </div>
    
</div>

{% endblock %}