about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('', views.about_detail, name='about_detail'),
    ]
   

bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls')),
    path('about/',include('about.urls')),
    path('accounts/',include('accounts.urls')),
    path('contact/',include('contact.urls')),
    path('',include('shop.urls', namespace="shop")),
    
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
]

contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.contact_detail, name='contact_detail'),
    ]
   

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
	path('recommend/',views.recommend,name='recommend'),
	path('', views.product_list, name='product_list'),
    path('<category_slug>/', views.product_list, name='product_list_by_category'),
   	path('<int:id>/<slug>/', views.product_detail, name='product_detail'),
   
   ]

shop/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import Permission, User
from django.core.validators import MaxValueValidator, MinValueValidator

class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True )
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    thumbnail = models.ImageField(upload_to='products/thumbnails', blank=True)
    author = models.CharField(max_length=50,db_index=True,default='Author_Name')
    publisher = models.CharField(max_length=50,db_index=True,default='Publisher_Name')
    isbn_no = models.CharField(max_length=50,db_index=True,default='isbn_no')

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

class Myrating(models.Model):
    user    = models.ForeignKey(User,related_name='rating',on_delete=models.CASCADE) 
    product = models.ForeignKey(Product,related_name='rated_products',on_delete=models.CASCADE)
    rating  = models.IntegerField(default=1,validators=[MaxValueValidator(5),MinValueValidator(0)])
    
    def __str__(self):
        return 'Rated Book: {}'.format(self.product)

    def get_absolute_url(self):
         return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.http import Http404, HttpResponse
from django.db.models import Q
from django.contrib.auth.models import User
from django.urls import reverse
from .models import Category, Product, Myrating
from django.contrib import messages
from cart.forms import CartAddProductForm
from django.db.models import Case, When
from .recommendation import Myrecommend
import numpy as np 
import pandas as pd

# for recommendation
def recommend(request):
    if not request.user.is_authenticated:
        return redirect("login")
    if not request.user.is_active:
        raise Http404
    
    df = pd.DataFrame(list(Myrating.objects.all().values('id', 'user_id', 'product_id', 'rating')))


    # Debugging: Check what columns exist
    print("DataFrame Columns:", df.columns)
    print("DataFrame Head:\n", df.head())

    if 'user_id' not in df.columns:
        return HttpResponse("Error: 'user_id' column is missing from the database data.", status=500)
    
    nu = df['user_id'].unique().shape[0]
    current_user_id= request.user.id
    
    # if new user not rated any movie
    # if current_user_id>=nu:
    #   product=Product.objects.get(id=15)
    #   q=Myrating(user=request.user,product=product,rating=4)
    #   q.save()

    print("Current user id: ",current_user_id)
    prediction_matrix,Ymean = Myrecommend()
    my_predictions = Ymean.flatten()
    pred_idxs_sorted = np.argsort(my_predictions)
    #reverse matrix
    pred_idxs_sorted[:] = pred_idxs_sorted[::-1]
    #increasing each value by 1
    pred_idxs_sorted=pred_idxs_sorted+1
    print(pred_idxs_sorted)
    preserved = Case(*[When(pk=pk, then=pos) for pos, pk in enumerate(pred_idxs_sorted)])
    product_list=list(Product.objects.filter(id__in = pred_idxs_sorted,).order_by(preserved)[:8])
    print(product_list)
    return render(request,'shop/recommend.html',{'product_list':product_list})
    

#List
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    search_term=''
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)
    
    if 'search' in request.GET:
        search_term = request.GET['search']
        products =  Product.objects.filter(name__icontains=search_term) 
        if products:
            messages.success(request,('You searched ') + search_term )
        else:
            messages.success(request, ('Book not found'))

    query  = request.GET.get('q')
    if query:
        products = Product.objects.filter(Q(title__icontains=query)).distinct()
        return render(request,'shop/list.html',{'products':products})

    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'search_term':search_term
    }
    return render(request, 'shop/list.html', context)

#detail
def product_detail(request, id, slug):
    if not request.user.is_authenticated:
        return redirect("login")
    if not request.user.is_active:
        raise Http404
    product = get_object_or_404(Product, id=id, slug=slug, available=True)

    cart_product_form = CartAddProductForm()
    
    #rating
    if request.method == "POST":
        rate =request.POST['rating']
        ratingObject = Myrating()
        ratingObject.user = request.user
        ratingObject.product = product
        ratingObject.rating = rate
        ratingObject.save()
        messages.success(request,"Your Rating is submited ")
        return redirect('shop:product_list')

    
    context = {
        'product': product,
        'cart_product_form': cart_product_form,
    }

    return render(request, 'shop/detail.html', context)
    

shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    
    
    <link rel="icon" href="{% static 'img/icon.png' %}">
    <title>{% block title %} BookBuzz - Online Bookstore| Home{% endblock %} </title>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' >
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    
    <style type="text/css">
        .thumbnail p, .thumbnail h4 {
            white-space: nowrap;
            text-overflow: ellipsis;
            overflow: hidden;
            }
        .star-rating {
            line-height:32px;
            font-size:1.25em;
            }

.star-rating .fa-star{color: gold;}
        
    </style>
    

    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="https://www.facebook.com/avhiaryal54" target="_blank"><i class="fab fa-facebook-f "></i></a>
                </li>
      
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fab fa-instagram"></i></a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fab fa-twitter"></i></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href=" http://www.youtube.com/c/AVHIARYAL" target="_blank"><i class="fab fa-youtube"></i></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" data-toggle="tooltip" data-placement="top" title="Call Us" href="tel:+9779840349182"><i class="fas fa-phone"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tooltip" data-placement="top" title="Mail Us" href="mailto:avhiaryal54@gmail.com"><i class="far fa-envelope"></i></a>
                </li>
            </ul>
            <ul class="navbar-nav md-auto">
                <p style="color: skyblue"><marquee behavior="scroll" direction="left" width="800">Informing. Educating. Inspiring. For the discerning reader.</marquee></p>

            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}"><i class="fas fa-user"></i> {{user.username}}</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
          
                    

                    <li class="nav-item">
                        {% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                                 <a class="nav-link" href="{% url 'cart:cart_detail' %}" style="color: red"><i class="fas fa-shopping-cart"></i>{{ total_items }}</a>
                            {% else %}
                                <a class="nav-link" href="{% url 'cart:cart_detail' %}" style="color: red"><i class="fas fa-shopping-cart"></i>0</a>
                                    
                            {% endif %}
                          {% endwith %}
                        </li>
                
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fas fa-shopping-cart"></i></a>
                    </li>

                {% endif %}
            </ul>
        </div>
    </nav>
   <!--  <div class="container-fluid"> -->
        <div class="row" style="margin-top:-3% ">
            <div class="col-1">
                <a class="navbar-brand" href="{% url 'shop:product_list' %}"><img src="{% static 'img/booklogo.png' %}" height="70" width="70"></a>
            </div>
        <div class="col-11" style="margin-top:2.6%">
            <nav class="navbar navbar-expand-lg navbar-light bg-info rounded">  
                          
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'shop:product_list' %}"><i class="fas fa-home" style="color: white"></i></a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'about:about_detail' %}" style="color: white" >About Us</a></li>
                <li  class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="avbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white" >Books</a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <ol class="list-unstyled">
                      <li {% if not category %} class="active"{% endif %}><a class="dropdown-item" style="color:red" href="{% url 'shop:product_list' %}">All Products</a></li>
                        {% for c in categories %}
                          <li {% if category.slug == slug %} class="active"{% endif %}><a  class="dropdown-item" href="{{ c.get_absolute_url }}" style="color: red">{{ c.name }}</a></li>
                        {% endfor %}
                    </ol>
                  </div>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'contact:contact_detail' %}" style="color: white" >Contact</a></li>
                <li class="nav-item"><a class="nav-link" href="https://avhiaryal54.wordpress.com/" target="_blank" style="color: white" >Blog</a></li>
                
                {% if user.is_authenticated %}
                    <li  class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="avbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white" >My Account</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <ol class="list-unstyled">
                                <li><a class="nav-link" href="{% url 'profile' %}" style="color:red">Profile</a></li>
                                <li> <a class="nav-link" href="{% url 'cart:cart_detail' %}" style="color: red">Cart:
                                    {% with total_items=cart|length %}
                                        {% if cart|length > 0 %}
                                            {{ total_items }} item{{ total_items|pluralize }}, Rs.{{ cart.get_total_price }}
                                        {% else %}
                                            0 items
                                        {% endif %}
                                    {% endwith %}</a>
                                </li>
                                <li><a href="{% url 'orders:order_create' %}" class="nav-link" style="color:red"> Checkout</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}" style="color:red">Logout</a></li>



                            </ol>
                        </div>
                    </li>
                {% endif %}

              </ul>
            </div>
                <ul class="navbar-nav ml-auto">
                  <form class="form-inline">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='search' value="{{search_term}}" size="50px">
                    <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
                  </form>
                </ul>
    </nav>
</div>
</div>
</div>


<div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-white">
    
</nav>
</div>

           
<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
</div>


{% block content %}

{% endblock %}
<hr>
<div class="copyright">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="copyright_content">
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | BookBuzz
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="{%static 'js/jquery.min.js'%}"></script>
<script type="text/javascript" src="{%static 'js/bootstrap.min.js'%}"></script>
<script type="text/javascript">
    var $star_rating = $('.star-rating .fa');
    var SetRatingStar = function()
    {
        return $star_rating.each(function()
        {
            if (parseInt($star_rating.siblings('input.rating-value').val()) >= parseInt($(this).data('rating')))
            {
                return $(this).removeClass('fa-star-o').addClass('fa-star');
            }
            else
            {
                return $(this).removeClass('fa-star').addClass('fa-star-o');
            }
        });
    };

    $star_rating.on('click', function()
    {
        $star_rating.siblings('input.rating-value').val($(this).data('rating'));
        return SetRatingStar();
    });

    SetRatingStar();
    $(document).ready(function(){
    });
        
</script>

<script type="text/javascript">
    function validateForm()
    {
        var x = document.forms["ratingForm"]["rating"].value;
        if(x=="0")
        {
            alert("Please Give Correct Rating");
            return false;
        }
    }
</script>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
</head>
</body>
</html>

shop/templates/shop/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}

  <div class="single_product" style="margin: 5%">
    <div class="container-fluid">
      <div class="row" style="margin-top: 2%">
        <div class="col">
            <div class="image_selected"><img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 500px; width: 500px">
          </div>
        </div>

        <div class="col">
          <h4><small>Have you read this book?</small></h4>
          <h5><small>Give your ratings to get recommendations</small></h5>
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-info alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
            {% endfor %}
          {% endif %}
          <form class="form-horizontal" role="search" method="post" action="" onsubmit="return validateForm()"  name="ratingForm">
            <div class="form-group">
              <div class="input-group">
                <div class="row">
                  <div class="col-lg-12">
                      <div class="star-rating">
                        <span class="fa fa-star-o" data-rating="1"></span>
                        <span class="fa fa-star-o" data-rating="2"></span>
                        <span class="fa fa-star-o" data-rating="3"></span>
                        <span class="fa fa-star-o" data-rating="4"></span>
                        <span class="fa fa-star-o" data-rating="5"></span>
                        <input type="hidden" name="rating" class="rating-value" value="0" >
                        {% csrf_token %}
                    </div>
                  </div>
                </div>
                <input type="submit" class="btn btn-info btn-sm" value="Rate" style="margin-left: 2%">
              </div>
            </div>
        </form>
        <br>
          <div class="product_description">
            <div class="product_category">
                <h4 style="margin-left: 40% ">Category</h4>
                <hr>
                <a class="btn btn-danger btn-lg btn-block" href="{{ product.category.get_absolute_url }}" role="button">{{ product.category }}</a>
            </div>
            <hr>
                
            <div class="product_name">
              <h3>{{ product.name }}</h3>  
            </div>
                    
            <div class="product_text">
              <p align="justify">{{ product.description|safe|linebreaksbr }}</p>
            </div>
            

            <div class="product_author">
              <p class="text-muted">Author: {{ product.author }}</p>
            </div>

            <div class="product_publisher">
              <p class="text-muted">Publisher: {{ product.publisher }}</p>
            </div>

            <div class="product_isbn_no">
              <p class="text-muted">ISBN: {{ product.isbn_no }}</p>
            </div>

            <div class="product_price">
              <p class="text-muted">Rs. {{ product.price }}</p>
            </div>
             {% if product.stock > 0 %}
                <div class="order_info d-flex flex-row">
                  <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    {% csrf_token %}
                    {{ cart_product_form }}
                    <input type="submit" value="Add to cart" class="btn btn-success btn-sm">
                  </form>
                </div>
             {% else %}
                <p class="card-text" style="color: red">This Product is Out of Stock</p>
             {% endif %} 
             <br>
             <hr>
          </div>      
         </div>
        </div>
      </div>
    </div>
    
{% endblock %}

shop/templates/shop/list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }} {% else %} BookBuzz - Online Bookstore| Home{% endif %}
{% endblock %}


{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <h5 style="text-align:center;color: grey ">Categories</h5>
      <br>
      <ul style="list-style: none">
        <li  {% if not category %}class="selected"{% endif %}>
         <a href="{% url 'shop:product_list' %}" class="dropdown-item">All Books</a>
        </li>  
        <hr>
        {% for c in categories %}
          <li {% if category.slug == slug %} class="active"{% endif %}>
            <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
          </li>
          <hr>
        {% endfor %} 
      </ul>                  
    </div>
    <div class="col-8">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="min-height: 0;min-width: 0">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'img/slide1.jpg' %}" alt="First slide">
          </div>
          
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/slide2.jpg' %}" alt="Second slide">
          </div>

          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/slide3.jpg' %}" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    <div class="col">
      <a href="{% url 'shop:recommend' %}" class="btn"><strong><p class="shadow p-1 mb-3 bg-light rounded"style="text-align:center;color: black ">Get Recommendations</p></strong></a>
      
    </div>
  </div>
</div>
<div class="container">
  <hr>  
</div>

<h4 class="shadow p-3 mb-1 bg-white rounded" align="center" style="color: grey ">ALL BOOKS</h4>
<div style="margin-top: 2%;margin-left: 6%">
  <div class="row">
    {% for product in products %}
    <div class="card text-black border-light mb-5" style="max-width: 18rem;margin-right: 2%">
      <div class="card-body">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %} {{ product.image.url }} {% else %}{% static 'img/no_image.png' %} {% endif %}" alt="..." style="height: 200px; width: 200px"></a>
        <hr>
        <h5 class="text-left">{{ product.name }}</h5>
        <p class="card-text">Rs. {{ product.price }}</p>
        {% if product.stock > 0 %}
          <p class="card-text" style="color: teal">In Stock</p>
        {% else %}
          <p class="card-text" style="color: gold">Out of Stock</p>
        {% endif %}
        <p><a href="{{ product.get_absolute_url }}" class="btn btn-dark btn-sm">View</a></p> 
          
      </div>
    </div>
    {% endfor %}
  </div>
</div>    
{% endblock %}

shop/templates/shop/recommend.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %} Recommendations {% endblock %}
{% block content %}

<div class="shadow p-3 mb-5 bg-light rounded">
    <h4 align="center" style="color: red">RECOMMENDATIONS FOR YOU</h4>
</div>

<div style="margin-top: 2%;margin-left: 6%">
  <div class="row">
    {% if product_list %}
      {% for product in product_list %}
        <div class="card text-black border-light mb-5" style="max-width: 18rem;margin-right: 2%">
            <div class="card-body">
                <a href="{{ product.get_absolute_url }}">
                  <img src="{% if product.image %} {{ product.image.url }} {% else %}{% static 'img/no_image.png' %} {% endif %}" alt="..." style="height: 200px; width: 200px">
                </a>
                <hr>
                <h5 class="text-left">{{ product.name }}</h5>
                <h6 class="text-left" style="color: red">{{ product.category }}</h6>
                <p class="card-text">Rs. {{ product.price }}</p>
                {% if product.stock > 0 %}
                  <p class="card-text" style="color: green">In Stock</p>
                {% else %}
                  <p class="card-text" style="color: green">Out of Stock</p>
                {% endif %}
                <p><a href="{{ product.get_absolute_url }}" class="btn btn-dark btn-sm">View</a></p> 
                
                  
            </div>
        </div>
      {% endfor %}
    {% endif %}

  </div>
</div>    


  

{% endblock %}